# Generated by Django 3.2.13 on 2022-06-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_devices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devices',
            options={'ordering': ('deviceName',)},
        ),
        migrations.AlterModelOptions(
            name='org',
            options={'ordering': ('orgId',)},
        ),
        migrations.AlterField(
            model_name='org',
            name='org',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
