# Generated by Django 3.2.13 on 2022-06-10 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220609_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='org',
            name='id',
        ),
        migrations.AlterField(
            model_name='org',
            name='orgId',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
